name: Flutter CI
on:
  push:
    branches:
      - main

jobs:
  build_apk:
    name: Build FLutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - name: Configure Keystore
        run: |
          cd android
          echo "$KEY_JKS" | base64 --decode > app/key.jks
          echo "storeFile=../app/key.jks" >> key.properties
          echo "keyAlias=$SIGNING_KEY_ALIAS" >> key.properties
          echo "storePassword=$SIGNING_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$SIGNING_KEY_PASSWORD" >> key.properties
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - name: Get dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

  beta_apk:
    name: Upload Android Beta to Firebase App Distribution
    needs: [build_apk]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: release-apk
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.4
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APPID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: alpha
          file: build/app/outputs/apk/release/app-release.apk
